[build]
builder = "nixpacks"
buildCommand = "cd server && npm ci && npm run build"

[deploy]
startCommand = "cd server && node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
