[build]
builder = "nixpacks"
builderVersion = "1.38.0"

[deploy]
startCommand = "cd server && node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
NIXPACKS_BUILD_CMD = "cd server && npm install && npm run build"
NIXPACKS_START_CMD = "cd server && node dist/index.js"
